import 'core-js/stable';
import 'regenerator-runtime/runtime';

import '@Fonts/compact-bold.woff';
import '@Fonts/open-sans-bold.woff';
import '@Fonts/open-sans.woff';
import '@Fonts/roboto-bold.woff';
import '@Fonts/roboto-regular.woff';
import '@Fonts/Glowgirl-Regular.woff2';
import '@Fonts/Vani.ttf';
import '@Fonts/Myriad Pro.ttf';
import '@Fonts/AthelasArabic-Regular.woff2';

import '@Styles/about-us.scss';
import '@Styles/advantages.scss';
import '@Styles/company-logo.scss';
import '@Styles/contact-us.scss';
import '@Styles/fonts.scss';
import '@Styles/footer.scss';
import '@Styles/header.scss';
import '@Styles/main.scss';
import '@Styles/nav.scss';
import '@Styles/our-team-leaders.scss';
import '@Styles/our-gallery.scss';

import '@Images/7ac905ca-f1ae-4a5b-b421-a32cce462281.jpg';
import '@Images/EGO-9_Page_008_Image_0002.jpg';
import '@Images/imanol-arias.jpg';
import '@Images/facebook.png';
import '@Images/google+.png';
import '@Images/phone.png';
import '@Images/twitter.png';
import '@Images/instagram.png';
import '@Images/map.png';
import '@Images/decisiones-en-los-negocios_1920.png';
import '@Images/decisiones-en-los-negocios_1440.jpg';
import '@Images/decisiones-en-los-negocios_1024.jpg';
import '@Images/Hands_Stock-150x150.jpg';
import '@Images/menschengruppe_klein.png';
import '@Images/shutterstock_116037967-Converted-150x150.jpg';
import '@Images/garantia-big_1000.jpg';
import '@Images/garantia-big_720.jpg';
import '@Images/garantia-big_520.jpg';
import '@Images/Website-Venture_Capitalist-1.jpg';
import '@Images/pexels-fauxels-3184292.jpg';
import '@Images/slide2.jpg';
import '@Images/hakkimizda.jpg';
